name: scout_maps
channels:
  - conda-forge
  - defaults
dependencies:
  - alabaster=0.7.12
  - altair=3.0.1
  - asn1crypto=0.24.0
  - attrs=19.1.0
  - babel=2.7.0
  - blas=1.0
  - boost-cpp=1.68.0
  - branca=0.3.1
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - cffi=1.12.3
  - cfitsio=3.430
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - cryptography=2.6.1
  - curl=7.64.1
  - cycler=0.10.0
  - descartes=1.1.0
  - docutils=0.14
  - entrypoints=0.3
  - expat=2.2.5
  - fiona=1.8.6
  - folium=0.9.1
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=2.4.1
  - geopandas=0.5.0
  - geos=3.7.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icu=58.1
  - idna=2.8
  - imagesize=1.1.0
  - intel-openmp=2019.3
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.1
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.64.1
  - libffi=3.2.1
  - libgdal=2.4.1
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libpq=11.3
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - lz4-c=1.8.3
  - mapclassify=2.0.1
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - matplotlib-base=3.1.0
  - mkl=2019.3
  - munch=2.3.2
  - numpy=1.16.3
  - olefile=0.46
  - openjpeg=2.3.1
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - pcre=8.41
  - pillow=6.0.0
  - pip=19.1.1
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.3
  - proj4=6.1.0
  - pycparser=2.19
  - pygments=2.4.2
  - pyopenssl=19.0.0
  - pyparsing=2.4.0
  - pyproj=2.1.3
  - pyqt=5.9.2
  - pyrsistent=0.15.2
  - pysocks=1.7.0
  - python=3.7.3
  - python-dateutil=2.8.0
  - pytz=2019.1
  - qt=5.9.7
  - requests=2.22.0
  - rtree=0.8.3
  - scipy=1.2.1
  - setuptools=41.0.1
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - snowballstemmer=1.2.1
  - sphinx=2.0.1
  - sphinx-gallery=0.3.1
  - sphinxcontrib-applehelp=1.0.1
  - sphinxcontrib-devhelp=1.0.1
  - sphinxcontrib-htmlhelp=1.0.2
  - sphinxcontrib-jsmath=1.0.1
  - sphinxcontrib-qthelp=1.0.2
  - sphinxcontrib-serializinghtml=1.1.1
  - sqlite=3.28.0
  - tk=8.6.9
  - toolz=0.9.0
  - tornado=6.0.2
  - urllib3=1.24.3
  - vincent=0.4.4
  - wheel=0.33.4
  - xerces-c=3.2.2
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.0
  - pip:
    - colorama==0.4.1
    - sphinx-rtd-theme==0.4.3
prefix: C:\Users\tyems\AppData\Local\conda\conda\envs\scout_maps
